### ISSUE TITLE
In Suse Linux Enterprise Server 15. SP3 it gives error executing xfs_undelete

### ISSUE THREAD

**Issue by psousadelta** [ianka/xfs_undelete#27] opened 2021-11-23 14:33 UTC
In Suse Linux Enterprise Server 15. SP3 it gives error executing xfs_undelete

Last sunday night (~21:30) by mistake i delete a linux virtual machine in Xen.
The host is a SUSE Linux Enterprise Server SP3 5.3.18-59.24 13-Sep-2021 with Xen, and the partition of /vm is in XFS format.
The virtual machine was in /vm/grpwise/ and the file was grpwise.qcow2 with 321G.

I am trying to use your tool xfs_undelete, but i cant make it running.
In the SLES 15 SP3 i've installed:
- tcl 8.6.7-7.6.1
- tk 8.6.7-3.6.3
- graphviz 2.40.1-6.12.1 and also i have made zypper install coreutils and he says it are installed (GNU Core Utils 8.29-2.12)
- also, tcl-devel

I'e copied shell.nix and xfs_undelete (the contents from you site) and made them exec with chmod 700
i run ./xfs_undelete and i receive:
can't find package cmdline
     while executing "package require cmdline"
    (file "./xfs_undelete" line 10)

I read something you said about this error, but i don't how to compile tcl 8.6 to make the modifications you said.....
I am not an "expert" in linux.
Can you give me support?
Wath would be the cost?
Thanks, 

Urgent  
Paulo Sousa / psousa@deltabyte.pt / Deltabyte

![20211122_182849](https://user-images.githubusercontent.com/94901383/143043156-007d9ad3-fc7c-477e-bbce-30355f8977d6.jpg)
![20211122_181758](https://user-images.githubusercontent.com/94901383/143043164-1d5a6327-d8a7-4fd8-9c24-4263ab9c4f7f.jpg)
![20211122_181821](https://user-images.githubusercontent.com/94901383/143043201-ae434c15-14fe-4079-b51f-634ed3e59e69.jpg)
e

**Comment by ianka** [comment] 2021-12-16 08:38
The problem is that your system somehow has done a linefeed translation. The LF chars (UInix line end markers) had been replaced by CR+LF chars (MS-Windows line end markers). That's how all lines end up with that extra \r(CR) char that mixes up things as soon the file is used on Unix again.

Have you by chance passed those files through an MS-Windows system? For example by downloading or unzipping them on MS-Windows? That would explain it.

**Comment by ianka** [comment] 2022-05-21 20:08
You haven't replied for a while. I'm closing this issue. Feel free to reopen it if you have new information.

**Closed as not planned by ianka** 2022-05-21 20:08 UTC
Labels: advice needed, no reply
