### ISSUE TITLE
The -S option appears to be ignored

### ISSUE THREAD

**Issue by nelgin** [ianka/xfs_undelete#56] opened 2024-08-28 09:30 UTC
```
# ./xfs_undelete /dev/vg00/lvmp3 -t ..-1hour -S 4000
```

I want to fetch files that were deleted less than an hour ago and have a size no greater than 4000 bytes.

```
-S size
Ignore files with a size larger than specified. The number may be given as bytes or with an appended k, M, G as kilobytes, megabytes, gigabytes respectively. By default there is no size limit.
```

-rw-r--r-- 1 root root 1151946752 Aug 28 04:26 2024-08-28-03-56_942712483.msvideo
-rw-r--r-- 1 root root  733483008 Aug 28 04:26 2024-08-28-03-56_942712484.msvideo
-rw-r--r-- 1 root root  733491200 Aug 28 04:27 2024-08-28-03-56_942712485.msvideo
-rw-r--r-- 1 root root  734269440 Aug 28 04:27 2024-08-28-03-56_942712486.msvideo
-rw-r--r-- 1 root root  734171136 Aug 28 04:27 2024-08-28-03-56_942712487.msvideo
-rw-r--r-- 1 root root  733556736 Aug 28 04:27 2024-08-28-03-56_942712488.msvideo

So why is it recovering huge video files ?

**Comment by ianka** [comment] 2024-08-28 12:53
Could you please insert

    puts stderr [list FFF $inode $::maxsize $filesize]

at [line 316](https://github.com/ianka/xfs_undelete/blob/master/xfs_undelete#L316l) of the script and try again?

**Comment by ianka** [comment] 2024-09-01 06:00
Ah, I got it. You have mixed up the order of the parameters and the options.

The argument `/dev/vg00/lvmp3` must **follow** the options `-t ..-1hour -S 4000` and not vice versa. This is a peculiarity of the command line parser and documented in the manpage. It's therefore not a bug. I remove the _bug spotted_ label and close the issue because of this.

(Yeah, it's not what most people would expect nowadays. The command line parser is a bit old-fashioned.)

**Closed as completed** 2024-09-01 06:01 UTC
Labels: advice needed, no reply
