### ISSUE TITLE
Can't figure if this tool is working.. please help.

### ISSUE THREAD

**Issue by brucethomax** [ianka/xfs_undelete#53] opened 2024-07-19 04:58 UTC
Attempting to recovery a folder that I (accidentally) removed using the terminal and taped "return" a little too quickly. I came across your repo and thought I'd get it a try.  Ideally it would be nice to narrow down the exact time (within a few minute timeframe) since the `rm` didn't take that long.

Using the following command(s) didn't recovery any files. 

```
 ./xfs_undelete -i "" -t -7hours -o undelete_sdc /dev/sdc1
````

1) is this correct for relative selection?

How do I know that this is working?? I have tried deleting another file (which is the only activity that this drive has had since the directory deletion) and that specific file deleted that was on `/dev/sdc1` was not recovered.

I've looked at the documentation and there might be a typo of `2hour` and I don't know what timeframe is selected to verify. Even a little print statement would help me here to verifythe right filter is being applied. I don't know this tcl lang or else I would try locally. Maybe I will if have some specific suggestions that I can try to figure out what is going on.

I have tried `-t "-7hours..now"` and `-t "-7hour..now"` as an alternate to above, still it didn't recover anything. Not sure since nothing was printed.

2) I have tried with and without the `-i ""` flag.

I am not really sure what this would do, either way it doesn't work. I just saw it on a [thread](https://github.com/ianka/xfs_undelete/issues/10) where you commended that. 

3) do you have a format between a 5 minute window? I couldn't find any documentation on how to do time formats for `clock scan`
 
I imagine that there is a parameter string that I could pass to `-t` that would be an exact 5 minute timeframe (with or without timezone) like `2024-07-18 13:00..2024-07-18 13:05` though there is no error -- I still don't know if this is working since there are no debug statements.

And after all that, thank you for your patience! I might just be hosed `"¯\_(ツ)_/¯"`, oh well.

**Comment by ianka** [comment] 2024-07-20 08:48
The time spec you used is correct for selecting all files deleted from 7 hours ago until now.

    $ tclsh <<<'puts [clock format [clock scan -2hours]]'

Those timespecs with .. have some extra string manipulation within xfs_undelete so you can't test them this way. The relevant code is at [line 421-441.](https://github.com/ianka/xfs_undelete/blob/master/xfs_undelete#L421-L441)

---

But I rather think that the problem is something different. For example, XFS filesystems in the wild differ in tiny details. Xfs_undelete has evolved over time to glance over those details but there may be still ways how your specific XFS deletes some sorts of files that are unknown to Xfs_undelete and thus, it cannot find them.

Xfs_undelete a pretty naïve program. It works for a large number of cases, it doesn't do anything to the filesystem so you can always try another tool later, and it's fast. But it does not guarantee you to find something to recover.

**Comment by ianka** [comment] 2024-07-20 14:02
I found there's an XFS feature called “bigtime” that  [changes the meaning of the timestamps in the inode](https://github.com/torvalds/linux/blob/master/fs/xfs/libxfs/xfs_format.h#L711-L791). Could you please check whether your filesystem has that option activated?

    $ xfs_info /dev/sdc1 | grep bigtime

**Comment by ianka** [comment] 2024-07-20 16:46
[I have just added support for the “bigtime” feature of recent XFS in the wild](https://github.com/ianka/xfs_undelete/commit/7e19828923248bed605434f1df352b23bca252dc).

Please try again with the latest version and give me a short reply whether that fixes your problem.

**Comment by brucethomax** [comment] 2024-07-21 04:18
> I found there's an XFS feature called “bigtime” that [changes the meaning of the timestamps in the inode](https://github.com/torvalds/linux/blob/master/fs/xfs/libxfs/xfs_format.h#L711-L791). Could you please check whether your filesystem has that option activated?
> 
> ```
> $ xfs_info /dev/sdc1 | grep bigtime
> ```

Thanks for the repsonse! Here is what I get.

```
# xfs_info /dev/sdc1 | grep bigtime
         =                       reflink=1    bigtime=1 inobtcount=1 nrext64=0
```
Using version v15 it starts recovering some stuff!! Yippy!

```
# ./xfs_undelete -t 2024-07-18..now -o undelete_sdc /dev/sdc1
Starting recovery.
Recovered file -> undelete_sdc/2024-07-19-11-02_25188506.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188510.java
Recovered file -> undelete_sdc/2024-07-19-11-02_25188513.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188518.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188523.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188538.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188540.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188541.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188542.txt
Recovered file -> undelete_sdc/2024-07-19-11-02_25188543.txt
^Cecking  inode   25188612 (  1%)
```

Would you happen to know the exact format that I can pick a specific date and time then add like +5min or +1hour. I will try out that `tclsh` a little bit, though I thought I would float the ask in this response! Thanks, again! :)

**Comment by ianka** [comment] 2024-07-21 15:17
Tcl's [clock scan] is pretty forgiving on the date string. For example you can write

    $ tclsh <<<'puts [clock format [clock scan 2024-07-20-6hours]]'
    Fri Jul 19 18:00:00 CEST 2024

or 

    $ tclsh <<<'puts [clock format [clock scan "07/19/2024 20:00-2hours"]]'
    Fri Jul 19 18:00:00 CEST 2024

**Comment by brucethomax** [comment] 2024-07-22 16:17
Thanks! I was able to recovery some files, thought it seems like many in a specific folder were not. Well, I suppose that is just the way it goes. Thanks for the help!

**Comment by ianka** [comment] 2024-07-22 20:02
I close this as resolved then. Thanks for pointing out the problem.

**Closed as completed by ianka** 2024-07-22 20:02 UTC
Labels: advice needed, resolved
